namespace: "pulp"
name: "squeezer"
authors:
  - "Matthias Dellweg <2500@gmx.de>"
  - "Timo Funke <timoses@msn.com>"
  - "Jacob Floyd <cognifloyd@gmail.com>"
  - "Yanis Guenane <yguenane@redhat.com>"
version: "0.0.7-dev"
license_file: LICENSE
readme: README.md
tags:
  - pulp
