namespace: "pulp"
name: "squeezer"
authors:
  - "Matthias Dellweg <2500@gmx.de>"
  - "Timo Funke <timoses@msn.com>"
  - "Jacob Floyd <cognifloyd@gmail.com>"
version: "0.0.3"
license_file: LICENSE
readme: README.md
tags:
  - pulp
